In [40]:
import pymongo
import pandas as pd

from pymongo import MongoClient

In [41]:
client = MongoClient()
#point the client at mongo URI
client = MongoClient()
#select database
db = client['nasjonalbibliografien']
#select the collection within the database
test = db.records

In [13]:
n = list(test.find().limit(10))

In [39]:
n[1]

{'_id': ObjectId('62fb7d423cc0fb0943f4787f'),
 'leader': '\n  01577ccm a2200433 c 4500\n ',
 'fields': [{'005': '\n  20211104092546.0\n '},
  {'007': '\n  qu\n '},
  {'008': '\n  150623s1999    no#||a||||||||||||||nob|\n '},
  {'001': '\n  990000486074702201\n '},
  {'015': {'subfields': [{'a': '\n   0007356\n  '}, {'2': '\n   nbf\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'024': {'subfields': [{'a': '\n   M-2610-1167-9\n  '}],
    'ind1': '2',
    'ind2': ' '}},
  {'028': {'subfields': [{'a': '\n   M-H 2857\n  '}],
    'ind1': '2',
    'ind2': '3'}},
  {'035': {'subfields': [{'a': '\n   000048607-47bibsys_network\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'035': {'subfields': [{'a': '\n   (NO-TrBIB)000048607\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'040': {'subfields': [{'a': '\n   NO-OsNB\n  '},
     {'b': '\n   nob\n  '},
     {'e': '\n   katreg\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'042': {'subfields': [{'a': '\n   norbibl\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'044': {'subfields': [{'c': '\n   no\n  '}], 'ind1': ' ', 'ind2': ' '}},
  {'082': {'subfields': [{'a': '\n   782.742\n  '},
     {'q': '\n   NO-OsNB\n  '},
     {'2': '\n   4/nor\n  '}],
    'ind1': '7',
    'ind2': '4'}},
  {'083': {'subfields': [{'a': '\n   782.14\n  '},
     {'q': '\n   NO-OsNB\n  '},
     {'2': '\n   4/nor\n  '}],
    'ind1': '7',
    'ind2': ' '}},
  {'084': {'subfields': [{'a': '\n   P 1\n  '}, {'2': '\n   noterlyd\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'100': {'subfields': [{'a': '\n   Knudsen, Per Egil\n  '},
     {'d': '\n   1950-\n  '},
     {'0': '\n   (NO-TrBIB)90325556\n  '}],
    'ind1': '1',
    'ind2': ' '}},
  {'245': {'subfields': [{'a': '\n   På byens runde torg\n  '},
     {'c': '\n   sangtekster: Inger Hagerup ; konseptidé og musikk: Per Egil Knudsen ; illustrasjon: Ragnhild Arneberg\n  '},
     {'h': '\n   [musikktrykk]\n  '}],
    'ind1': '1',
    'ind2': '0'}},
  {'260': {'subfields': [{'a': '\n   Oslo\n  '},
     {'b': '\n   Musikkhusets forl.\n  '},
     {'c': '\n   c1999\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'300': {'subfields': [{'a': '\n   36 s.\n  '},
     {'b': '\n   ill.\n  '},
     {'c': '\n   30 cm\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'380': {'subfields': [{'a': '\n   Barnemusikk\n  '},
     {'2': '\n   emnmus\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'382': {'subfields': [{'a': '\n   Klaver\n  '},
     {'a': '\n   Sang\n  '},
     {'2': '\n   emnmus\n  '}],
    'ind1': ' ',
    'ind2': '1'}},
  {'382': {'subfields': [{'a': '\n   Sang\n  '}, {'2': '\n   emnmus\n  '}],
    'ind1': ' ',
    'ind2': '1'}},
  {'500': {'subfields': [{'a': '\n   Tekst og melodistemme med tekst og besifring\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'500': {'subfields': [{'a': '\n   Overtittel: Barnemusikkteater\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'500': {'subfields': [{'a': '\n   Platenummer: M-H 2857\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'533': {'subfields': [{'a': '\n   Elektronisk reproduksjon\n  '},
     {'b': '\n   [Norge]\n  '},
     {'c': '\n   Nasjonalbiblioteket Digital\n  '},
     {'d': '\n   2019-07-25\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'653': {'subfields': [{'a': '\n   barn\n  '},
     {'a': '\n   musikk\n  '},
     {'a': '\n   sanger\n  '},
     {'a': '\n   musikkteater\n  '},
     {'a': '\n   inger\n  '},
     {'a': '\n   hagerup\n  '},
     {'a': '\n   musikkspillsyngespill\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'700': {'subfields': [{'a': '\n   Hagerup, Inger\n  '},
     {'d': '\n   1905-1985\n  '},
     {'4': '\n   aut\n  '},
     {'0': '\n   (NO-TrBIB)90534304\n  '}],
    'ind1': '1',
    'ind2': ' '}},
  {'740': {'subfields': [{'a': '\n   Barnemusikkteater\n  '}],
    'ind1': '0',
    'ind2': ' '}},
  {'856': {'subfields': [{'3': '\n   Fulltekst\n  '},
     {'u': '\n   https://www.nb.no/search?q=oaiid:"oai:nb.bibsys.no:990000486074702202"&mediatype=bøker\n  '},
     {'y': '\n   Nettbiblioteket\n  '},
     {'z': '\n   Søke-URL\n  '}],
    'ind1': '4',
    'ind2': '1'}},
  {'901': {'subfields': [{'a': '\n   90\n  '}], 'ind1': ' ', 'ind2': ' '}},
  {'913': {'subfields': [{'a': '\n   Musikk\n  '}, {'b': '\n   NB\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'913': {'subfields': [{'a': '\n   Nornoter\n  '}, {'b': '\n   NB\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'991': {'subfields': [{'a': '\n   volumes\n  '}],
    'ind1': ' ',
    'ind2': ' '}}]}

In [37]:
for x in pd.json_normalize(n).iloc[8]:
    if isinstance(x, list):
        for y in x:
            print(y)
    else:
        print(x)

62fb7d423cc0fb0943f47886

  02091cam a2200541 c 4500

{'005': '\n  20211031111009.0\n '}
{'007': '\n  ta\n '}
{'007': '\n  cr||||||||||||\n '}
{'008': '\n  140705s1999    no#||||| |||||000|0bnno|\n '}
{'001': '\n  990000454624702201\n '}
{'015': {'subfields': [{'a': '\n   0008181\n  '}, {'2': '\n   nbf\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'020': {'subfields': [{'a': '\n   8203181767\n  '}, {'q': '\n   ib.\n  '}, {'c': '\n   Nkr 198.00\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'035': {'subfields': [{'a': '\n   000045462-47bibsys_network\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'035': {'subfields': [{'a': '\n   (NO-TrBIB)000045462\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'035': {'subfields': [{'a': '\n   (NO-TrBIB)092112153\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'035': {'subfields': [{'a': '\n   (NOLOHIST)20010000019499\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'035': {'subfields': [{'a': '\n   (ANNO)8739\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'040': {'subfields': [{'a': '\n   NO-OsNB\n  '}, {'b': '\n   nob\n  '}, {'e': '\n   katreg\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'042': {'subfields': [{'a': '\n   norbibl\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'044': {'subfields': [{'c': '\n   no\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'080': {'subfields': [{'a': '\n   315.644\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'080': {'subfields': [{'a': '\n   929\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'080': {'subfields': [{'a': '\n   39\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'082': {'subfields': [{'a': '\n   920.71\n  '}, {'q': '\n   NO-OsNB\n  '}, {'2': '\n   4/nor\n  '}], 'ind1': '7', 'ind2': '4'}}
{'084': {'subfields': [{'a': '\n   Kf 35f(Jc 30)\n  '}, {'2': '\n   ubtkl/2\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'084': {'subfields': [{'a': '\n   Vdd\n  '}, {'2': '\n   knt\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'100': {'subfields': [{'a': '\n   Bjerkem, Johan Einar\n  '}], 'ind1': '1', 'ind2': ' '}}
{'245': {'subfields': [{'a': '\n   Portrett av ein historieforteljar :\n  '}, {'b': '\n   samtalar med Ragnar Ryan\n  '}, {'c': '\n   Johan Einar Bjerkem ; [teikningar: Kari Barstad]\n  '}], 'ind1': '1', 'ind2': '0'}}
{'260': {'subfields': [{'a': '\n   [Oslo]\n  '}, {'b': '\n   Norsk folkeminnelag\n  '}, {'b': '\n   Aschehoug\n  '}, {'c': '\n   1999\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'300': {'subfields': [{'a': '\n   136 s.\n  '}, {'b': '\n   ill.\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'490': {'subfields': [{'a': '\n   Norsk folkeminnelags skrifter\n  '}, {'v': '\n   nr 146\n  '}], 'ind1': '1', 'ind2': ' '}}
{'533': {'subfields': [{'a': '\n   Elektronisk reproduksjon\n  '}, {'b': '\n   [Norge]\n  '}, {'c': '\n   Nasjonalbiblioteket Digital\n  '}, {'d': '\n   2009-04-20\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'600': {'subfields': [{'a': '\n   Ryan, Ragnar\n  '}, {'0': '\n   (NO-TrBIB)2086\n  '}, {'2': '\n   bare\n  '}], 'ind1': '1', 'ind2': '7'}}
{'653': {'subfields': [{'a': '\n   folkeminne\n  '}, {'a': '\n   historie\n  '}, {'a': '\n   historiefortelling\n  '}, {'a': '\n   folketro\n  '}, {'a': '\n   sagn\n  '}, {'a': '\n   steinkjer\n  '}, {'a': '\n   nord-trøndelag\n  '}, {'a': '\n   ogndal\n  '}, {'a': '\n   henning\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'651': {'subfields': [{'a': '\n   Norge\n  '}, {'2': '\n   humord\n  '}, {'0': '\n   (NO-TrBIB)HUME02605\n  '}], 'ind1': ' ', 'ind2': '7'}}
{'655': {'subfields': [{'a': '\n   Myter\n  '}, {'2': '\n   humord\n  '}, {'0': '\n   (NO-TrBIB)HUME01106\n  '}], 'ind1': ' ', 'ind2': '7'}}
{'655': {'subfields': [{'a': '\n   Sagn\n  '}, {'2': '\n   humord\n  '}, {'0': '\n   (NO-TrBIB)HUME01112\n  '}], 'ind1': ' ', 'ind2': '7'}}
{'650': {'subfields': [{'a': '\n   Folketro\n  '}, {'2': '\n   humord\n  '}, {'0': '\n   (NO-TrBIB)HUME05087\n  '}], 'ind1': ' ', 'ind2': '7'}}
{'650': {'subfields': [{'a': '\n   Memorat\n  '}, {'2': '\n   humord\n  '}, {'0': '\n   (NO-TrBIB)HUME05035\n  '}], 'ind1': ' ', 'ind2': '7'}}
{'650': {'subfields': [{'a': '\n   Folklore\n  '}, {'2': '\n   humord\n  '}, {'0': '\n   (NO-TrBIB)HUME04969\n  '}], 'ind1': ' ', 'ind2': '7'}}
{'700': {'subfields': [{'a': '\n   Ryan, Ragnar\n  '}], 'ind1': '1', 'ind2': ' '}}
{'700': {'subfields': [{'a': '\n   Barstad, Kari\n  '}, {'4': '\n   ill\n  '}], 'ind1': '1', 'ind2': ' '}}
{'830': {'subfields': [{'a': '\n   Norsk folkeminnelags skrifter (trykt utg.)\n  '}, {'x': '\n   0800-5826\n  '}, {'v': '\n   nr 146\n  '}, {'w': '\n   998121800034702201\n  '}], 'ind1': ' ', 'ind2': '0'}}
{'856': {'subfields': [{'3': '\n   Beskrivelse fra Forlagssentralen\n  '}, {'u': '\n   http://content.bibsys.no/content/?type=descr_forlagssentr&isbn=8203181767\n  '}], 'ind1': '4', 'ind2': '2'}}
{'856': {'subfields': [{'3': '\n   Fulltekst\n  '}, {'u': '\n   https://www.nb.no/search?q=oaiid:"oai:nb.bibsys.no:990000454624702202"&mediatype=bøker\n  '}, {'y': '\n   Nettbiblioteket\n  '}, {'z': '\n   Søke-URL\n  '}], 'ind1': '4', 'ind2': '1'}}
{'901': {'subfields': [{'a': '\n   90\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'913': {'subfields': [{'a': '\n   Norbok\n  '}, {'b': '\n   NB\n  '}], 'ind1': ' ', 'ind2': ' '}}
{'913': {'subfields': [{'a': '\n   Norsk lokalhistorisk institutt\n  '}, {'b': '\n   NB\n  '}], 'ind1': ' ', 'ind2': ' '}}

In [29]:
pd.json_normalize(n, record_path='fields', meta=['leader'], max_level=1)

,005,007,008,001,035.subfields,035.ind1,035.ind2,040.subfields,040.ind1,040.ind2,...,830.subfields,830.ind1,830.ind2,080.subfields,080.ind1,080.ind2,655.subfields,655.ind1,655.ind2,leader
0,\n 20210315104833.0\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 00880cam a22002531c 4500\n
1,NaN,\n ta\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 00880cam a22002531c 4500\n
2,NaN,NaN,\n 150709s1965 no |||||||||||000|u|nob|d\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 00880cam a22002531c 4500\n
3,NaN,NaN,NaN,\n 990000480974702201\n,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 00880cam a22002531c 4500\n
4,NaN,NaN,NaN,NaN,[{'a': ' 000048097-47bibsys_network '}],,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 00880cam a22002531c 4500\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 01031cam a2200277 c 4500\n
255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 01031cam a2200277 c 4500\n
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 01031cam a2200277 c 4500\n
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 01031cam a2200277 c 4500\n
258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\n 01031cam a2200277 c 4500\n

In [26]:
pd.json_normalize(n)

,_id,leader,fields
0,62fb7d423cc0fb0943f4787e,\n 00880cam a22002531c 4500\n,"[{'005': ' 20210315104833.0 '}, {'007': ' ..."
1,62fb7d423cc0fb0943f4787f,\n 01577ccm a2200433 c 4500\n,"[{'005': ' 20211104092546.0 '}, {'007': ' ..."
2,62fb7d423cc0fb0943f47880,\n 01263cam a2200313 c 4500\n,"[{'005': ' 20210223145757.0 '}, {'007': ' ..."
3,62fb7d423cc0fb0943f47881,\n 01435cam a2200385 c 4500\n,"[{'005': ' 20211031172744.0 '}, {'007': ' ..."
4,62fb7d423cc0fb0943f47882,\n 00782cam a2200253 c 4500\n,"[{'005': ' 20170124085818.0 '}, {'007': ' ..."
5,62fb7d423cc0fb0943f47883,\n 01443cam a2200385 c 4500\n,"[{'005': ' 20211101101941.0 '}, {'007': ' ..."
6,62fb7d423cc0fb0943f47884,\n 00719cam a22002297c 4500\n,"[{'005': ' 20211103125019.0 '}, {'007': ' ..."
7,62fb7d423cc0fb0943f47885,\n 00846cam a2200289 c 4500\n,"[{'005': ' 20160620182733.0 '}, {'007': ' ..."
8,62fb7d423cc0fb0943f47886,\n 02091cam a2200541 c 4500\n,"[{'005': ' 20211031111009.0 '}, {'007': ' ..."
9,62fb7d423cc0fb0943f47887,\n 01031cam a2200277 c 4500\n,"[{'005': ' 20210710031445.0 '}, {'007': ' ..."

In [23]:
pd.json_normalize(pd.json_normalize(n).fields)

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,{'005': ' 20210315104833.0 '},{'007': ' ta '},{'008': ' 150709s1965 no |||||||||||000|u...,{'001': ' 990000480974702201 '},{'035.subfields': [{'a': ' 000048097-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000048...,"{'040.subfields': [{'a': ' NO-TrBIB '}, {...","{'044.subfields': [{'c': ' no '}], '044.i...","{'100.subfields': [{'a': ' Michalsen, Fin ...","{'245.subfields': [{'a': ' Slekten : '}, ...",...,None,None,None,None,None,None,None,None,None,None
1,{'005': ' 20211104092546.0 '},{'007': ' qu '},{'008': ' 150623s1999 no#||a|||||||||||||...,{'001': ' 990000486074702201 '},"{'015.subfields': [{'a': ' 0007356 '}, {'...",{'024.subfields': [{'a': ' M-2610-1167-9 ...,"{'028.subfields': [{'a': ' M-H 2857 '}], ...",{'035.subfields': [{'a': ' 000048607-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000048...,"{'040.subfields': [{'a': ' NO-OsNB '}, {'...",...,"{'991.subfields': [{'a': ' volumes '}], '...",None,None,None,None,None,None,None,None,None
2,{'005': ' 20210223145757.0 '},{'007': ' ta '},{'008': ' 120515s1975 no#|||||||||||000|0...,{'001': ' 990000498674702201 '},"{'015.subfields': [{'a': ' 751130 '}, {'2...",{'035.subfields': [{'a': ' 000049867-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000049...,"{'040.subfields': [{'a': ' NO-TrBIB '}, {...","{'041.subfields': [{'a': ' nob '}, {'a': ...","{'044.subfields': [{'c': ' no '}], '044.i...",...,None,None,None,None,None,None,None,None,None,None
3,{'005': ' 20211031172744.0 '},{'007': ' ta '},{'007': ' cr|||||||||||| '},{'008': ' 121017s1999 no#||||| |||||000|0...,{'001': ' 990000523454702201 '},"{'015.subfields': [{'a': ' 0005967 '}, {'...","{'020.subfields': [{'q': ' h. '}], '020.i...",{'035.subfields': [{'a': ' 000052345-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000052...,{'035.subfields': [{'a': ' (NO-TrBIB)122947...,...,None,None,None,None,None,None,None,None,None,None
4,{'005': ' 20170124085818.0 '},{'007': ' ta '},{'008': ' 130227s1962 no#|||||||||||000|0...,{'001': ' 990000494094702201 '},"{'015.subfields': [{'a': ' 6202630 '}, {'...",{'035.subfields': [{'a': ' 000049409-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000049...,"{'040.subfields': [{'a': ' NO-TrBIB '}, {...","{'044.subfields': [{'c': ' no '}], '044.i...","{'082.subfields': [{'a': ' 920 '}, {'q': ...",...,None,None,None,None,None,None,None,None,None,None
5,{'005': ' 20211101101941.0 '},{'007': ' ta '},{'007': ' cr|||||||||||| '},{'008': ' 110105s1999 no ||||| |||||000|0...,{'001': ' 990000525744702201 '},"{'015.subfields': [{'a': ' 0013280 '}, {'...","{'020.subfields': [{'a': ' 8279110194 '},...",{'035.subfields': [{'a': ' 000052574-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000052...,{'035.subfields': [{'a': ' (NO-TrBIB)092035...,...,None,None,None,None,None,None,None,None,None,None
6,{'005': ' 20211103125019.0 '},{'007': ' ta '},{'008': ' 100126s1945 no#|||||||||||000|u...,{'001': ' 990000537404702201 '},"{'015.subfields': [{'a': ' 4502330 '}, {'...",{'035.subfields': [{'a': ' 000053740-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000053...,"{'040.subfields': [{'a': ' NO-OsNB '}, {'...","{'044.subfields': [{'c': ' no '}], '044.i...","{'100.subfields': [{'a': ' Johansen, Syver ...",...,None,None,None,None,None,None,None,None,None,None
7,{'005': ' 20160620182733.0 '},{'007': ' ta '},{'008': ' 010330s1998 xx#|||||||||||000|0...,{'001': ' 990000453064702201 '},"{'015.subfields': [{'a': ' 0107863 '}, {'...","{'020.subfields': [{'a': ' 4757150040 '},...",{'035.subfields': [{'a': ' 000045306-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000045...,"{'040.subfields': [{'a': ' NO-OsNB '}, {'...","{'042.subfields': [{'a': ' norbibl '}], '...",...,None,None,None,None,None,None,None,None,None,None
8,{'005': ' 20211031111009.0 '},{'007': ' ta '},{'007': ' cr|||||||||||| '},{'008': ' 140705s1999 no#||||| |||||000|0...,{'001': ' 990000454624702201 '},"{'015.subfields': [{'a': ' 0008181 '}, {'...","{'020.subfields': [{'a': ' 8203181767 '},...",{'035.subfields': [{'a': ' 000045462-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000045...,{'035.subfields': [{'a': ' (NO-TrBIB)092112...,...,"{'650.subfields': [{'a': ' Memorat '}, {'...","{'650.subfields': [{'a': ' Folklore '}, {...","{'700.subfields': [{'a': ' Ryan, Ragnar '...","{'700.subfields': [{'a': ' Barstad, Kari ...",{'830.subfields': [{'a': ' Norsk folkeminne...,{'856.subfields': [{'3': ' Beskrivelse fra ...,"{'856.subfields': [{'3': ' Fulltekst '}, ...","{'901.subfields': [{'a': ' 90 '}], '901.i...","{'913.subfields': [{'a': ' Norbok '}, {'b...",{'913.subfields': [{'a': ' Norsk lokalhisto...
9,{'005': ' 20210710031445.0 '},{'007': ' ta '},{'008': ' 110523s1972 no#|||||||||||000|0...,{'001': ' 990000514704702201 '},"{'015.subfields': [{'a': ' 7203402 '}, {'...","{'015.subfields': [{'a': ' 7202128 '}, {'...",{'035.subfields': [{'a': ' 000051470-47bibs...,{'035.subfields': [{'a': ' (NO-TrBIB)000051...,"{'040.subfields': [{'a': ' NO-TrBIB '}, {...","{'044.subfields': [{'c': ' no '}], '044.i...",...,None,None,None,None,None,None,None,None,None,None

In [10]:
#convert entire collection to Pandas dataframe
t = pd.DataFrame(list(n))

In [11]:
t

,_id,leader,fields
0,62fb7d423cc0fb0943f4787e,\n 00880cam a22002531c 4500\n,"[{'005': ' 20210315104833.0 '}, {'007': ' ..."
1,62fb7d423cc0fb0943f4787f,\n 01577ccm a2200433 c 4500\n,"[{'005': ' 20211104092546.0 '}, {'007': ' ..."
2,62fb7d423cc0fb0943f47880,\n 01263cam a2200313 c 4500\n,"[{'005': ' 20210223145757.0 '}, {'007': ' ..."
3,62fb7d423cc0fb0943f47881,\n 01435cam a2200385 c 4500\n,"[{'005': ' 20211031172744.0 '}, {'007': ' ..."
4,62fb7d423cc0fb0943f47882,\n 00782cam a2200253 c 4500\n,"[{'005': ' 20170124085818.0 '}, {'007': ' ..."
5,62fb7d423cc0fb0943f47883,\n 01443cam a2200385 c 4500\n,"[{'005': ' 20211101101941.0 '}, {'007': ' ..."
6,62fb7d423cc0fb0943f47884,\n 00719cam a22002297c 4500\n,"[{'005': ' 20211103125019.0 '}, {'007': ' ..."
7,62fb7d423cc0fb0943f47885,\n 00846cam a2200289 c 4500\n,"[{'005': ' 20160620182733.0 '}, {'007': ' ..."
8,62fb7d423cc0fb0943f47886,\n 02091cam a2200541 c 4500\n,"[{'005': ' 20211031111009.0 '}, {'007': ' ..."
9,62fb7d423cc0fb0943f47887,\n 01031cam a2200277 c 4500\n,"[{'005': ' 20210710031445.0 '}, {'007': ' ..."

In [56]:
cur = test.find({"fields.700.subfields.a" : "\n   Ibsen, Henrik\n  " }).limit(10)

l = list(cur)

In [69]:
pd.json_normalize(l, ["fields"], ['_id', "leader"])

,005,007,008,001,015.subfields,015.ind1,015.ind2,035.subfields,035.ind1,035.ind2,...,240.ind1,240.ind2,382.subfields,382.ind1,382.ind2,600.subfields,600.ind1,600.ind2,_id,leader
0,\n 20160620182807.0\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d443cc0fb0943f48102,\n 00764cam a2200253 c 4500\n
1,NaN,\n ta\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d443cc0fb0943f48102,\n 00764cam a2200253 c 4500\n
2,NaN,NaN,\n 150910s1981 xx#|||||||||||000|0|chi|\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d443cc0fb0943f48102,\n 00764cam a2200253 c 4500\n
3,NaN,NaN,NaN,\n 990002472784702201\n,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d443cc0fb0943f48102,\n 00764cam a2200253 c 4500\n
4,NaN,NaN,NaN,NaN,"[{'a': ' 8104206 '}, {'2': ' nbf '}]",,,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d443cc0fb0943f48102,\n 00764cam a2200253 c 4500\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'a': ' Ibsen, Henrik '}, {'d': ' 182...",1,7,62fb7d483cc0fb0943f48e09,\n 00932cam a2200313 c 4500\n
276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d483cc0fb0943f48e09,\n 00932cam a2200313 c 4500\n
277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d483cc0fb0943f48e09,\n 00932cam a2200313 c 4500\n
278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d483cc0fb0943f48e09,\n 00932cam a2200313 c 4500\n
279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62fb7d483cc0fb0943f48e09,\n 00932cam a2200313 c 4500\n

In [77]:
pd.json_normalize(l[1], ["fields", "subfields"], max_level=0)

KeyError: "Key 'subfields' not found. If specifying a record_path, all elements of data should have the path."

In [57]:
pd.DataFrame(l)

,_id,leader,fields
0,62fb7d443cc0fb0943f48102,\n 00764cam a2200253 c 4500\n,"[{'005': ' 20160620182807.0 '}, {'007': ' ..."
1,62fb7d463cc0fb0943f48644,\n 01529cjm a2200373 c 4500\n,"[{'005': ' 20150605160013.0 '}, {'007': ' ..."
2,62fb7d463cc0fb0943f48731,\n 02616cam a2200529 c 4500\n,"[{'005': ' 20160622111720.0 '}, {'007': ' ..."
3,62fb7d463cc0fb0943f48741,\n 01589cam a2200409 c 4500\n,"[{'005': ' 20160622111720.0 '}, {'007': ' ..."
4,62fb7d463cc0fb0943f487d5,\n 01489ccm a2200457 c 4500\n,"[{'005': ' 20150605160013.0 '}, {'007': ' ..."
5,62fb7d463cc0fb0943f48803,\n 01567ccm a2200445 c 4500\n,"[{'005': ' 20150605160013.0 '}, {'007': ' ..."
6,62fb7d473cc0fb0943f488ba,\n 00913cam a2200301 c 4500\n,"[{'005': ' 20170124085635.0 '}, {'007': ' ..."
7,62fb7d473cc0fb0943f48966,\n 00909cam a2200265 c 4500\n,"[{'005': ' 20160622111729.0 '}, {'007': ' ..."
8,62fb7d483cc0fb0943f48cf7,\n 00915cam a2200277 c 4500\n,"[{'005': ' 20170124092652.0 '}, {'007': ' ..."
9,62fb7d483cc0fb0943f48e09,\n 00932cam a2200313 c 4500\n,"[{'005': ' 20170124084344.0 '}, {'007': ' ..."

In [59]:
l[9]

{'_id': ObjectId('62fb7d483cc0fb0943f48e09'),
 'leader': '\n  00932cam a2200313 c 4500\n ',
 'fields': [{'005': '\n  20170124084344.0\n '},
  {'007': '\n  ta\n '},
  {'008': '\n  150605s2000    xx#|||||||||||000|0|mul|\n '},
  {'001': '\n  990006580904702201\n '},
  {'015': {'subfields': [{'a': '\n   0007295\n  '}, {'2': '\n   nbf\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'035': {'subfields': [{'a': '\n   00065809x-47bibsys_network\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'035': {'subfields': [{'a': '\n   (NO-TrBIB)00065809x\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'040': {'subfields': [{'a': '\n   NO-OsNB\n  '},
     {'b': '\n   nob\n  '},
     {'e': '\n   katreg\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'041': {'subfields': [{'a': '\n   swe\n  '}, {'a': '\n   nob\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'042': {'subfields': [{'a': '\n   norbibl\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'044': {'subfields': [{'c': '\n   se\n  '}], 'ind1': ' ', 'ind2': ' '}},
  {'082': {'subfields': [{'a': '\n   839.822\n  '},
     {'q': '\n   NO-OsNB\n  '},
     {'2': '\n   4/nor\n  '}],
    'ind1': '7',
    'ind2': '4'}},
  {'100': {'subfields': [{'a': '\n   Åkerman, Henrik\n  '},
     {'0': '\n   (NO-TrBIB)26013\n  '}],
    'ind1': '1',
    'ind2': ' '}},
  {'245': {'subfields': [{'a': '\n   Henrik Ibsen - sanning och konsekvens\n  '}],
    'ind1': '1',
    'ind2': '0'}},
  {'260': {'subfields': [{'a': '\n   [Stockholm]\n  '},
     {'b': '\n   [H. Åkerman]\n  '},
     {'c': '\n   [2000]\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'300': {'subfields': [{'a': '\n   36 bl.\n  '}], 'ind1': ' ', 'ind2': ' '}},
  {'500': {'subfields': [{'a': '\n   Tekstutdrag på norsk\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'500': {'subfields': [{'a': '\n   Skrevet av Henrik Åkerman\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'500': {'subfields': [{'a': '\n   Omhandler hovedsakelig Ibsens Peer Gynt\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'600': {'subfields': [{'a': '\n   Ibsen, Henrik\n  '},
     {'d': '\n   1828-1906\n  '},
     {'t': '\n   Peer Gynt\n  '},
     {'0': '\n   (NO-TrBIB)90061718\n  '},
     {'2': '\n   bare\n  '}],
    'ind1': '1',
    'ind2': '7'}},
  {'700': {'subfields': [{'a': '\n   Ibsen, Henrik\n  '},
     {'d': '\n   1828-1906\n  '},
     {'t': '\n   Peer Gynt\n  '},
     {'0': '\n   (NO-TrBIB)90061718\n  '}],
    'ind1': '1',
    'ind2': '2'}},
  {'901': {'subfields': [{'a': '\n   90\n  '}], 'ind1': ' ', 'ind2': ' '}},
  {'913': {'subfields': [{'a': '\n   Ibsensamlingen\n  '},
     {'b': '\n   NB\n  '}],
    'ind1': ' ',
    'ind2': ' '}},
  {'913': {'subfields': [{'a': '\n   Norbok\n  '}, {'b': '\n   NB\n  '}],
    'ind1': ' ',
    'ind2': ' '}}]}